"""Pipeline orchestration.

    intake -> classification -> route selection -> operator execution
    -> evidence and contradiction gate -> convergence -> metacognitive audit
    -> recommendation -> authorization gate -> decision receipt

The router is deterministic end to end. Operator *content* arrives through an
adapter so that a model can supply it later without any routing logic moving
into the model; v0.1 ships a fixture adapter so runs are byte-reproducible.
What the engine executes in either case is the operator *contract*: input
validation, required transformations, evidence binding, confidence ceilings,
and prohibited-behavior checks.
"""
from copy import deepcopy
from pathlib import Path
from typing import Any

from . import audit as audit_module
from . import authorization as auth_module
from . import contradiction as contradiction_module
from . import converge as converge_module
from . import evidence as evidence_module
from .classify import classify, extract_signals
from .contracts import enforce
from .intake import normalize_intake, intake_hash
from .io import digest, load_json
from .ledger import append_idempotent, seen_nonces
from .normalize import normalize_evidence_record
from .paths import SCHEMA_DIR
from .policy import load_controls
from .router import select_route
from .schema_validation import SchemaValidationError, load_and_validate
from .stages import StageChain


class RunError(RuntimeError):
    pass


def _effective(claim: dict[str, Any], register, policy, task_class, operator_id) -> dict[str, Any]:
    factors = policy["confidence_model"]["factors"]
    declared = claim.get("declared_confidence", "unknown")
    ceiling_info = evidence_module.ceiling(claim.get("evidence_refs", []), register, policy, task_class)
    declared_factor = factors.get(declared, 0.0)
    return {
        "claim_id": claim["claim_id"],
        "operator_id": operator_id,
        "statement": claim["statement"],
        "polarity": claim.get("polarity", "neutral"),
        "subject_ref": claim.get("subject_ref"),
        "evidence_refs": sorted(set(claim.get("evidence_refs", []))),
        "declared_confidence": declared,
        "declared_confidence_factor": declared_factor,
        "evidence_ceiling": ceiling_info["ceiling"],
        "effective_confidence": round(min(declared_factor, ceiling_info["ceiling"]), 6),
        "evidence_profile": ceiling_info,
    }


def run(run_input_path: Path, ledger_path: Path | None = None, verifier=None) -> dict[str, Any]:
    raw = load_json(run_input_path)
    load_and_validate(raw, SCHEMA_DIR / "run-input.schema.json")

    controls = load_controls()
    policy = controls["policy"]
    registry = controls["registry"]

    if raw.get("policy_version") != policy["version"] or raw.get("operator_registry_version") != registry["version"]:
        raise RunError("RCP-FAIL-VERSION-UNKNOWN: run input targets a different policy or operator registry version")

    run_id = raw["run_id"]
    run_timestamp = raw["run_timestamp"]

    intake = normalize_intake(deepcopy(raw["intake"]))
    normalized_hash = intake_hash(intake)

    signals = extract_signals(intake, policy)
    classification = classify(intake, policy)
    route = select_route(classification, signals, controls)

    records = [normalize_evidence_record(item) for item in deepcopy(raw.get("evidence_register", []))]
    for record in records:
        load_and_validate(record, SCHEMA_DIR / "evidence-record.schema.json")
    register = evidence_module.build_register(records)

    chain = StageChain()
    stage_contents: dict[int, dict[str, Any]] = {}

    def seal(stage: str, operator_id: str, version: str, status: str, content: dict[str, Any]) -> None:
        record = chain.append(stage, operator_id, version, status, content, run_timestamp)
        stage_contents[record["sequence"]] = content

    seal("INTAKE", "intake", "0.1.0", "COMPLETE", {"normalized_intake_hash": normalized_hash, "signals": signals})
    seal("CLASSIFY", "classifier", policy["version"], "COMPLETE", classification)

    if not route["route_supported"]:
        return _unsupported_receipt(
            raw, intake, normalized_hash, signals, classification, route, controls, chain, ledger_path
        )

    seal("ROUTE", "router", policy["version"], "COMPLETE", route)

    # The option set grows as the route runs. Options generated by an EXPLORE
    # operator join the set that CHALLENGE, FORECAST, and DECIDE work over,
    # which is what stops divergent from being decorative: a generated option
    # is ranked, challenged, and rejected on the record like any other.
    options = [{**option, "origin": "intake"} for option in intake["options"]]
    option_ids = {option["option_id"] for option in options}
    observation_ids = {item["observation_id"] for item in intake["observations"]}
    supplied = raw.get("operator_outputs", {})

    executed: list[str] = []
    violations: list[dict[str, Any]] = []
    claims: list[dict[str, Any]] = []
    operator_conclusions: list[dict[str, Any]] = []
    boundary_flags: set[str] = set()
    assumptions: list[dict[str, Any]] = []
    partial: list[dict[str, Any]] = []

    for step in route["operators"]:
        operator_id = step["operator_id"]
        if operator_id in {"convergent", "metacognitive"}:
            continue
        contract = controls["operators_by_id"][operator_id]
        payload = deepcopy(supplied.get(operator_id))

        if payload is None:
            partial.append({"operator_id": operator_id, "status": "NOT_EXECUTED", "detail": "no operator output supplied by the adapter"})
            seal(step["stage"], operator_id, contract["version"], "NOT_EXECUTED", {"operator_id": operator_id})
            continue

        ctx = {
            "policy": policy,
            "option_ids": option_ids,
            "observation_ids": observation_ids,
            "evidence_ids": set(register),
            "claim_ids": {claim["claim_id"] for claim in claims},
            "subject_ids": {item["hypothesis_id"] for item in payload.get("hypotheses", [])} | observation_ids,
        }
        # A structurally invalid payload is a contract violation, not a crash.
        # The route continues so the audit sees the whole picture, and the gate
        # forces REVIEW because a required operator did not meet its contract.
        found: list[dict[str, Any]] = []
        try:
            load_and_validate(payload, SCHEMA_DIR / "operator-output.schema.json")
        except SchemaValidationError as exc:
            found.append({"operator_id": operator_id, "code": "GLOBAL-SCHEMA", "detail": str(exc)})

        found.extend(enforce(operator_id, contract, payload, ctx))
        violations.extend(found)
        status = "CONTRACT_VIOLATION" if found else "COMPLETE"

        if contract["output_contract"]["produces_options"]:
            for generated in payload.get("options", []):
                if generated["option_id"] not in option_ids:
                    options.append({**generated, "origin": f"generated_by:{operator_id}"})
                    option_ids.add(generated["option_id"])

        ingestible = [
            claim
            for claim in payload.get("claims", [])
            if isinstance(claim, dict) and claim.get("claim_id") and claim.get("statement")
        ]
        if len(ingestible) != len(payload.get("claims", [])):
            found.append(
                {
                    "operator_id": operator_id,
                    "code": "GLOBAL-CLAIM-MALFORMED",
                    "detail": "a claim lacked a claim_id or statement and was not admitted to the run",
                }
            )
            violations.append(found[-1])
        resolved = [
            _effective(claim, register, policy, classification["task_class"], operator_id)
            for claim in ingestible
        ]
        claims.extend(resolved)
        executed.append(operator_id)
        boundary_flags.update(payload.get("boundary_flags", []))
        for assumption in payload.get("assumptions", []):
            assumptions.append({"operator_id": operator_id, "assumption": assumption, "treated_as": "missing_evidence"})

        conclusion = {
            "operator_id": operator_id,
            "operator_version": contract["version"],
            "stage": step["stage"],
            "status": status,
            "selection_basis": step["selection_basis"],
            "selection_rationale": step["selection_rationale"],
            "declared_confidence": payload.get("declared_confidence"),
            "effective_confidence": round(max((claim["effective_confidence"] for claim in resolved), default=0.0), 6),
            "structured_payload_key": contract["output_contract"]["structured_payload_key"],
            "structured_payload": payload.get(contract["output_contract"]["structured_payload_key"], []),
            "claims": resolved,
            "assumptions": payload.get("assumptions", []),
            "contract_violations": found,
        }
        operator_conclusions.append(conclusion)
        seal(step["stage"], operator_id, contract["version"], status, conclusion)

    contradictions = contradiction_module.detect(claims, policy)

    convergence = converge_module.converge(
        options, claims, register, contradictions, policy, classification["task_class"]
    )
    seal("DECIDE", "convergent", controls["operators_by_id"]["convergent"]["version"], "COMPLETE", convergence)
    executed.append("convergent")

    missing_evidence = _missing_evidence(convergence, assumptions, register)

    planned = [step["operator_id"] for step in route["operators"] if step["operator_id"] != "metacognitive"]
    audit_result = audit_module.run_audit(
        planned_operators=planned,
        executed_operators=executed,
        violations=violations,
        claims=claims,
        contradictions=contradictions,
        convergence=convergence,
        authorization={"derived_from_confidence": False},
        missing_evidence=missing_evidence,
        chain=chain,
        stage_contents=stage_contents,
        policy=policy,
    )
    seal("AUDIT", "metacognitive", controls["operators_by_id"]["metacognitive"]["version"], "COMPLETE", audit_result)
    executed.append("metacognitive")

    gate = _apply_gate(
        boundary_flags=sorted(boundary_flags),
        audit_result=audit_result,
        violations=violations,
        partial=partial,
        convergence=convergence,
        contradictions=contradictions,
        signals=signals,
        policy=policy,
    )

    recommendation = _recommendation(convergence, gate, options)
    receipt_binding = digest(
        {"run_id": run_id, "recommendation": recommendation["statement"], "option_id": recommendation["option_id"]}
    )

    authorization = auth_module.evaluate(
        requested_action=intake.get("requested_action"),
        authorization=raw.get("casa_authorization"),
        verifier=verifier or auth_module.UnavailableVerifier(),
        run_timestamp=run_timestamp,
        receipt_binding=receipt_binding,
        seen_nonces=seen_nonces(ledger_path),
    )
    composition = auth_module.compose_execution(
        gate_result=gate["gate_result"],
        evidence_sufficient=convergence["selected_option_id"] is not None,
        authorization_status=authorization["status"],
    )

    receipt = _receipt(
        raw=raw,
        controls=controls,
        intake=intake,
        normalized_hash=normalized_hash,
        signals=signals,
        classification=classification,
        route=route,
        register=register,
        operator_conclusions=operator_conclusions,
        claims=claims,
        assumptions=assumptions,
        contradictions=contradictions,
        missing_evidence=missing_evidence,
        convergence=convergence,
        audit_result=audit_result,
        gate=gate,
        recommendation=recommendation,
        options=options,
        receipt_binding=receipt_binding,
        authorization=authorization,
        composition=composition,
        partial=partial,
        chain=chain,
    )
    load_and_validate(receipt, SCHEMA_DIR / "decision-receipt.schema.json")
    receipt["ledger_receipt"] = append_idempotent(ledger_path, receipt)
    return receipt


# --------------------------------------------------------------------------


def _missing_evidence(convergence, assumptions, register) -> list[dict[str, Any]]:
    items: list[dict[str, Any]] = []
    for option in convergence["ranking"]:
        for unmet in option["unmet_thresholds"]:
            items.append(
                {
                    "kind": "evidence_threshold",
                    "subject_ref": option["option_id"],
                    "detail": f"{option['option_id']}: {unmet}",
                }
            )
    for assumption in assumptions:
        items.append(
            {
                "kind": "undischarged_assumption",
                "subject_ref": assumption["operator_id"],
                "detail": f"{assumption['operator_id']} assumed without evidence: {assumption['assumption']}",
            }
        )
    return items


def _apply_gate(boundary_flags, audit_result, violations, partial, convergence, contradictions, signals, policy) -> dict[str, Any]:
    thresholds = policy["confidence_thresholds"]
    high_impact = bool(set(signals) & set(thresholds["high_impact_signals"]))
    required = thresholds["minimum_for_high_impact_recommendation"] if high_impact else thresholds["minimum_for_recommendation"]
    unresolved = contradiction_module.unresolved_material(contradictions)

    checks = [
        (bool(boundary_flags), "HALT", "RCP-GATE-BOUNDARY-FLAG", f"boundary flags raised: {boundary_flags}"),
        (audit_result["audit_result"] == "FAIL", "REVIEW", "RCP-GATE-AUDIT-FAIL", f"metacognitive audit failed with {audit_result['material_finding_count']} material findings"),
        (bool(violations) or bool(partial), "REVIEW", "RCP-GATE-ROUTE-INCOMPLETE", "an operator violated its contract or did not execute"),
        (convergence["selected_option_id"] is None and not convergence["tie_candidates"], "REVIEW", "RCP-GATE-EVIDENCE-INSUFFICIENT", convergence["selection_reason"]),
        (bool(unresolved), "REVIEW", "RCP-GATE-CONTRADICTION-UNRESOLVED", f"{len(unresolved)} unresolved material contradiction(s)"),
        (convergence["selected_option_id"] is not None and convergence["decision_confidence"] < required, "REVIEW", "RCP-GATE-CONFIDENCE-BELOW-THRESHOLD", f"decision confidence {convergence['decision_confidence']} is below the required {required}"),
        (bool(convergence["tie_candidates"]), "REVIEW", "RCP-GATE-MATERIAL-TIE", f"tied options {convergence['tie_candidates']}"),
    ]

    reasons = [{"reason_code": code, "detail": detail, "gate": result} for fired, result, code, detail in checks if fired]
    if any(item["gate"] == "HALT" for item in reasons):
        gate_result = "HALT"
    elif reasons:
        gate_result = "REVIEW"
    else:
        gate_result = "ALLOW"
        reasons = [{"reason_code": "RCP-GATE-ELIGIBLE-FOR-HUMAN-REVIEW", "detail": "all gates cleared", "gate": "ALLOW"}]

    return {
        "gate_result": gate_result,
        "gate_reasons": reasons,
        "confidence_threshold_applied": required,
        "high_impact_route": high_impact,
        "allow_semantics": policy["allow_semantics"],
    }


def _recommendation(convergence, gate, options) -> dict[str, Any]:
    if gate["gate_result"] == "HALT":
        return {
            "statement": "Do not proceed. A boundary condition was raised and this run cannot produce an actionable recommendation.",
            "option_id": None,
            "kind": "HALT",
        }
    if convergence["selected_option_id"] is None:
        return {
            "statement": f"No recommendation. {convergence['selection_reason']}. Route to human review with the missing-evidence list.",
            "option_id": None,
            "kind": "NO_RECOMMENDATION",
        }
    option = next(item for item in options if item["option_id"] == convergence["selected_option_id"])
    prefix = "Recommend" if gate["gate_result"] == "ALLOW" else "Provisionally recommend, pending human review"
    return {
        "statement": f"{prefix}: {option['label']}. {convergence['selection_reason']}.",
        "option_id": option["option_id"],
        "kind": "RECOMMENDATION",
    }


def _unsupported_receipt(raw, intake, normalized_hash, signals, classification, route, controls, chain, ledger_path) -> dict[str, Any]:
    receipt = {
        "receipt_version": "0.1.0",
        "run_id": raw["run_id"],
        "run_timestamp": raw["run_timestamp"],
        "problem_statement": intake["problem_statement"],
        "normalized_intake_hash": normalized_hash,
        "signals": signals,
        "classification": classification,
        "versions": {
            "policy_id": controls["policy"]["policy_id"],
            "policy_version": controls["policy"]["version"],
            "operator_registry_id": controls["registry"]["registry_id"],
            "operator_registry_version": controls["registry"]["version"],
            "operator_registry_sha256": controls["checksums"]["operator_registry_sha256"],
            "routing_policy_sha256": controls["checksums"]["routing_policy_sha256"],
        },
        "route": route,
        "evidence_used": [],
        "operator_conclusions": [],
        "assumptions": [],
        "contradictions": [],
        "missing_evidence": [
            {"kind": "coverage_gap", "subject_ref": "classification", "detail": route["coverage_gap_statement"]}
        ],
        "confidence_by_operator": [],
        "convergence": {
            "ranking": [],
            "selected_option_id": None,
            "rejected_alternatives": [],
            "decision_confidence": 0.0,
            "decision_confidence_label": controls["policy"]["confidence_model"]["label"],
        },
        "metacognitive_audit": {
            "operator_id": "metacognitive",
            "audit_result": "FAIL",
            "material_finding_count": 1,
            "findings": [
                {
                    "finding_id": "MC-F1",
                    "phase": "PLAN",
                    "severity": "material",
                    "detail": "no supported route exists for this classification",
                }
            ],
            "coverage": {"planned_operators": [], "executed_operators": [], "route_depth": 0},
        },
        "gate": {
            "gate_result": "REVIEW",
            "gate_reasons": [
                {
                    "reason_code": route["coverage_gap_reason"],
                    "detail": route["coverage_gap_statement"],
                    "gate": "REVIEW",
                }
            ],
            "confidence_threshold_applied": 0.0,
            "high_impact_route": False,
            "allow_semantics": controls["policy"]["allow_semantics"],
        },
        "recommendation": {
            "statement": "No recommendation. The intake does not match any supported task classification, so no reasoning route was run.",
            "option_id": None,
            "kind": "NO_RECOMMENDATION",
        },
        "risks": [],
        "authorization": {
            "status": "NOT_REQUESTED",
            "reason": "no route ran, so no action can be recommended",
            "verifier": "unavailable",
            "verifier_is_authentic": False,
            "checks": [],
            "derived_from_confidence": False,
        },
        "execution": {
            "execution_outcome": "REVIEW",
            "execution_authorized": False,
            "recommendation_eligible": False,
            "authorization_status": "NOT_REQUESTED",
            "composition_rule": "confidence never grants permission; authorization never cures insufficient evidence",
        },
        "review_requirements": ["A human must supply a supported classification or extend the routing policy."],
        "next_action": "Route to the decision owner to restate the problem within a supported task classification.",
        "stage_chain": chain.records,
        "stage_chain_head": chain.head,
        "partial_execution": [],
        "record_id": f"{raw['run_id']}::UNSUPPORTED",
    }
    receipt["ledger_receipt"] = append_idempotent(ledger_path, receipt)
    return receipt


def _receipt(**kwargs) -> dict[str, Any]:
    raw = kwargs["raw"]
    controls = kwargs["controls"]
    convergence = kwargs["convergence"]
    gate = kwargs["gate"]
    audit_result = kwargs["audit_result"]
    policy = controls["policy"]

    risks: list[dict[str, Any]] = []
    for conclusion in kwargs["operator_conclusions"]:
        if conclusion["operator_id"] == "inverted":
            for mode in conclusion["structured_payload"]:
                risks.append(
                    {
                        "risk_id": mode.get("failure_mode_id"),
                        "source_operator": "inverted",
                        "statement": mode.get("statement", mode.get("precondition", "")),
                        "reversible": mode.get("reversible"),
                        "detection_signal": mode.get("detection_signal"),
                        "boundary_flag_candidate": mode.get("boundary_flag_candidate"),
                    }
                )
        if conclusion["operator_id"] == "second-order":
            for effect in conclusion["structured_payload"]:
                risks.append(
                    {
                        "risk_id": effect.get("effect_id"),
                        "source_operator": "second-order",
                        "statement": effect.get("statement", ""),
                        "reversible": None,
                        "detection_signal": None,
                        "horizon": effect.get("horizon"),
                        "affected_party": effect.get("affected_party"),
                    }
                )

    review_requirements = [reason["detail"] for reason in gate["gate_reasons"] if reason["gate"] != "ALLOW"]
    if kwargs["authorization"]["status"] in {"PENDING_CASA", "VERIFICATION_UNAVAILABLE", "DENIED"}:
        review_requirements.append(f"Authorization is {kwargs['authorization']['status']}: {kwargs['authorization']['reason']}")

    next_action = {
        "ALLOW": "Present the recommendation and its receipt to the decision owner for approval.",
        "REVIEW": "Route to the decision owner with the missing-evidence and contradiction lists before any action.",
        "HALT": "Stop. Escalate the boundary condition to the decision owner.",
    }[gate["gate_result"]]

    return {
        "receipt_version": "0.1.0",
        "run_id": raw["run_id"],
        "run_timestamp": raw["run_timestamp"],
        "problem_statement": kwargs["intake"]["problem_statement"],
        "normalized_intake_hash": kwargs["normalized_hash"],
        "signals": kwargs["signals"],
        "classification": kwargs["classification"],
        "versions": {
            "policy_id": policy["policy_id"],
            "policy_version": policy["version"],
            "operator_registry_id": controls["registry"]["registry_id"],
            "operator_registry_version": controls["registry"]["version"],
            "operator_registry_sha256": controls["checksums"]["operator_registry_sha256"],
            "routing_policy_sha256": controls["checksums"]["routing_policy_sha256"],
        },
        "route": kwargs["route"],
        "option_set": [
            {"option_id": option["option_id"], "label": option["label"], "origin": option["origin"]}
            for option in sorted(kwargs["options"], key=lambda item: item["option_id"])
        ],
        "evidence_used": [
            {
                "evidence_id": record["evidence_id"],
                "source_type": record["source_type"],
                "authority": record["authority"],
                "quality": record["quality"],
                "independence_group": record["independence_group"],
                "verification_state": record["verification_state"],
                "untrusted_instruction_detected": record.get("untrusted_instruction_detected", False),
            }
            for record in sorted(kwargs["register"].values(), key=lambda item: item["evidence_id"])
        ],
        "operator_conclusions": [
            {
                "operator_id": conclusion["operator_id"],
                "operator_version": conclusion["operator_version"],
                "stage": conclusion["stage"],
                "status": conclusion["status"],
                "selection_basis": conclusion["selection_basis"],
                "selection_rationale": conclusion["selection_rationale"],
                "conclusions": [claim["statement"] for claim in conclusion["claims"]],
                "structured_payload_key": conclusion["structured_payload_key"],
                "structured_payload": conclusion["structured_payload"],
                "contract_violations": conclusion["contract_violations"],
            }
            for conclusion in kwargs["operator_conclusions"]
        ],
        "assumptions": kwargs["assumptions"],
        "contradictions": kwargs["contradictions"],
        "missing_evidence": kwargs["missing_evidence"],
        "confidence_by_operator": [
            {
                "operator_id": conclusion["operator_id"],
                "declared_confidence": conclusion["declared_confidence"],
                "effective_confidence": conclusion["effective_confidence"],
                "contributes_to_decision_confidence": conclusion["operator_id"]
                in policy["confidence_model"]["decision_confidence_contributors"],
            }
            for conclusion in kwargs["operator_conclusions"]
        ]
        + [
            {
                "operator_id": "convergent",
                "declared_confidence": "derived",
                "effective_confidence": convergence["decision_confidence"],
                "contributes_to_decision_confidence": True,
            }
        ],
        "convergence": {
            "ranking": convergence["ranking"],
            "selected_option_id": convergence["selected_option_id"],
            "rejected_alternatives": convergence["rejected_alternatives"],
            "tie_candidates": convergence["tie_candidates"],
            "selection_reason": convergence["selection_reason"],
            "decision_confidence": convergence["decision_confidence"],
            "decision_confidence_basis": convergence["decision_confidence_basis"],
            "decision_confidence_label": convergence["decision_confidence_label"],
            "thresholds_applied": convergence["thresholds_applied"],
        },
        "metacognitive_audit": audit_result,
        "gate": gate,
        "recommendation": kwargs["recommendation"],
        "recommendation_binding_hash": kwargs["receipt_binding"],
        "risks": risks,
        "authorization": kwargs["authorization"],
        "execution": kwargs["composition"],
        "review_requirements": review_requirements,
        "next_action": next_action,
        "stage_chain": kwargs["chain"].records,
        "stage_chain_head": kwargs["chain"].head,
        "partial_execution": kwargs["partial"],
        "record_id": f"{raw['run_id']}::{convergence['selected_option_id'] or 'NO_RECOMMENDATION'}",
    }
